### PR TITLE
Remove deprecated usage of ioutil

### PR DESCRIPTION
**Pull request by noqcks**
https://github.com/go-critic/go-critic/issues/1019

### CODE REVIEW

**Review by shibumi — APPROVED** [review]

**Comment by shibumi** [comment]
@sschuberth  this one needs manual approval for the CI jobs, too :(

**Comment by sschuberth** [comment]
> @sschuberth this one needs manual approval for the CI jobs, too :(

I don't think so... it just says "Some checks haven’t completed yet" but tests seem to hang in the "Waiting for status to be reported" state indefinitely. Maybe the PR is based on a state that does not have the new 1.19/20 tests yet? If so, it just needs to be rebased.

**Comment by shibumi** [comment]
@sschuberth I am pretty sure it's the same error message like the one in the other 2 PRs: "Expected — Waiting for status to be reported".

**Comment by sschuberth** [comment]
> @sschuberth I am pretty sure it's the same error message like the one in the other 2 PRs: "Expected — Waiting for status to be reported".

But this time (in contrast to [here](https://github.com/package-url/packageurl-go/pull/50)) it's the *new* 1.19/20 checks that do not start.

I currently don't understand why I don't have the UI to rebase the PR / update it with `main` myself. I'll check the settings.

**Comment by shibumi** [comment]
@sschuberth this button was not visible for me. Any chance I can get permission for this. Pinging you all the time is a little bit toilsome and I am sure you would get annoyed by it on the long run :D

**Comment by shibumi** [comment]
image

Ah never mind. I see the buttons now.

**Comment by sschuberth** [comment]
> @sschuberth this button was not visible for me.

As I wrote above, I *wasn't* seeing them either 😉

**Pull request merged**
